### ISSUE TITLE
Create upgrade instructions to get from old master to new master 

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#103]
@randalburns @kunallillaney 

The setup for the django part of OCP appears to have changed somewhat significantly. I am unable to run master on my local dev environment (see #98 )

These changes seem large enough that we should consider making this v0.7.1 or something similar...

**Comment by kunallillaney** [comment]
There is no new setup. pip install blosc and requests and get the new makefile.

**Comment by alexbaden** [comment]
That doesn't explain the changes in settings.py and settings_secret.py

**Comment by kunallillaney** [comment]
All private settings have now moved to settings_secret. We no longer have a settings example. Everything private goes to secret.
