### ISSUE TITLE
decide on how to downsample images going forward

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#104]
pending comments from misha & guillermo

**Comment by jovo** [comment]
misha says: 
"Bilinear is the standard.
Higher order (e.g. bicubic and antialias) would likely give better looking results at the cost of a small amount of smoothing.
Assuming that you are resampling images and not labels, I would avoid using nearest neighbor interpolation."

i vote "we" take a relatively small dataset, and try all 4, and compare both visually and computationally (ie, both how long it takes, and how it changes accuracy on some task, eg, synapse detection).  obviously not urgently.  maybe something @Aeusman & @j6k4m8 could try?

@randalburns @kunallillaney what do you think?

**Comment by willgray** [comment]
Nearest neighbor is nice because it's conceptually simple and doesn't
introduce new information.  Obviously a huge deal for labels, and less so
here, although we use the same downsample code for both code paths - anno
and image - which is nice, especially in light of everything being a
channel.

Bicubic is slower but often "better" than bilinear.

Seems like a fine experiment to try.  I wonder if Albert noticed specific
things he didn't like in the data, or if it's a general preference?

Best,
Will

On Wed, Aug 26, 2015 at 6:28 AM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
well, anno != labels exactly
it seems to me that even with NN, we have to threshold or something to
choose the label; given that, which ever kernel one uses, we still have to
threshold?

On Wed, Aug 26, 2015 at 7:00 AM, William Gray <notifications@github.com>
wrote:

> Nearest neighbor is nice because it's conceptually simple and doesn't
> introduce new information. Obviously a huge deal for labels, and less so
> here, although we use the same downsample code for both code paths - anno
> and image - which is nice, especially in light of everything being a
> channel.
>
> Bicubic is slower but often "better" than bilinear.
>
> Seems like a fine experiment to try. I wonder if Albert noticed specific
> things he didn't like in the data, or if it's a general preference?
>
> Best,
> Will
>
> On Wed, Aug 26, 2015 at 6:28 AM, joshua vogelstein <
> notifications@github.com
> > wrote:
>
> > misha says:
> > "Bilinear is the standard.
> > Higher order (e.g. bicubic and antialias) would likely give better
> looking
> > results at the cost of a small amount of smoothing.
> > Assuming that you are resampling images and not labels, I would avoid
> > using nearest neighbor interpolation."
> >
> > i vote "we" take a relatively small dataset, and try all 4, and compare
> > both visually and computationally (ie, both how long it takes, and how it
> > changes accuracy on some task, eg, synapse detection). obviously not
> > urgently. maybe something @Aeusman <https://github.com/Aeusman> &
> @j6k4m8
> > <https://github.com/j6k4m8> could try?
> >
> > @randalburns <https://github.com/randalburns> @kunallillaney
> > <https://github.com/kunallillaney> what do you think?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/open-connectome/issues/104#issuecomment-134936724
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/104#issuecomment-134948701>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York>

**Comment by jovo** [comment]
PIL by default does NN, but misha says bilinear makes more sense for images:
http://pillow.readthedocs.org/en/3.0.x/reference/Image.html#PIL.Image.Image.resize

at some point, we should do the experiment.
might be good for a rotation student or something.
