### ISSUE TITLE
Documentation Updates (non-urgent)

### ISSUE THREAD

**Issue by willgray** [openconnectome/open-connectome#106]
- RAMON Queries
- the overlay docs point to the cutout service

**Comment by kunallillaney** [comment]
Can we have one TODO for docs. There seems to be 5-6 floating around.

**Comment by jovo** [comment]
@kunallillaney you want all docs issues to be documented in a single repo, rather than in their respective repo's? i'm fine with whatever, just let me know

**Comment by kunallillaney** [comment]
No. But between you and @willgray there are 3 open for this repo itself.

**Comment by jovo** [comment]
@willgray @kunallillaney tell me where to post issues, and i'll do that.

**Comment by willgray** [comment]
ah - but we git issue as we find them, so that they are individual actions
that can be closed?

Best,
Will

**Comment by kunallillaney** [comment]
#106, #100, #84 are all different?

**Comment by jovo** [comment]
yup, sorry, i can clarify in person if you want...

**Comment by jovo** [comment]
@willgray this particular issue is quite unclear to me and kunal.
can you please use good issue posting practice, with sufficient level of detail to enable easy rectification, eg, include which file you are referring to, what is the problem, etc.?

**Comment by willgray** [comment]
Fair enough.

1.  RAMON Docs are not complete:
http://openconnectome.github.io/open-connectome/api/ramon_api.html

2.  Overlay docs talk about a "cutut service"  - but even with the typo
fixed, do you want to say cutout service (because specifically designed for
browser, I guess?)

3.  Not sure where id filter and spatial filter query docs live. Can you
help me?


Best,
Will

On Wed, Aug 26, 2015 at 6:49 PM, joshua vogelstein <notifications@github.com
