### ISSUE TITLE
dataset parameters and bounds checking

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#108]
http://openconnecto.me/ocp/ca/kharris15apical/info/

Using res 3, we have: 
x: 0,1024
y: 0,1024
z: 0,194

http://openconnecto.me/ocp/ca/kharris15apical/image/xy/3/0,1024/0,1024/193/ works
http://openconnecto.me/ocp/ca/kharris15apical/image/xy/3/0,1024/0,1024/194/ does not

is slice 194 the last slice in the dataset, or 1 past the last slice in the dataset? Presumably there is data at  (1024,1024) and (0,0) in x,y? 

http://openconnecto.me/ocp/ca/kharris15apical/image/xy/3/1024,1025/1024,1025/193/ does not work. 

If I wanted to get the very last voxel in slice 193, what command would I run? 
If I wanted to get the very last slice (193 or 194? I need to go back and check the raw data to confirm what it actually should be, but am curious what the dataset parameters above tell you it should be), what cutout would I run? 

( @randalburns @j6k4m8 @willgray )

**Comment by kunallillaney** [comment]
slice 193 is slice 192 in the RESTful call because your numbering starts form 0. Thus 194 slices translates to 193. Same for 1024 and not 1025.

**Comment by alexbaden** [comment]
So the very last voxel in the dataset is (1023,1023,193) ?

**Comment by kunallillaney** [comment]
http://openconnecto.me/ocp/ca/kharris15apical/image/hdf5/3/1023,1024/1023,1024/193,194/

**Comment by alexbaden** [comment]
Great, so CAJAL should be consistent with this now.

If the offset were 1, that wouldn't change anything, right? My slices would
just go from slice #1 to slice #193 instead of slice #0 to slice #193 (I'd
have 1 less slice).

**Comment by kunallillaney** [comment]
No that would change everything. It would go to slice 194 then.

**Comment by alexbaden** [comment]
So the last voxel is (dimension + offset - 1) for x, y, and z.

**Comment by alexbaden** [comment]
Is my last comment correct?

**Comment by kunallillaney** [comment]
Yes. But you need to give a range of +1 to get it. Look at the hdf5 call I wrote.

**Comment by alexbaden** [comment]
Where is the hdf5 call? 

Another bounds question -- are timesteps the same? For example:

starttime = 0
endtime = 8000

Is there data at both 0 and 8000? DOes that change if starttime = 1 and endtime = 8000?

**Comment by kunallillaney** [comment]
http://openconnecto.me/ocp/ca/kharris15apical/image/hdf5/3/1023,1024/1023,1024/193,194/ This one.

starttime = 0 endtime = 8000
Yes there is data between 0 and 8000 

starttime = 1 and endtime = 8000
Yes there is data between 1 and 8000

**Comment by alexbaden** [comment]
Right, of course -- but you should never give a value that is greater than
(dimension + offset - 1). I think we can close this guy now. I'll update
CAJAL.
