### ISSUE TITLE
Token Creation

### ISSUE THREAD

**Issue by willgray** [openconnectome/open-connectome#11]
What's our strategy for users to get tokens/projects?

Do we want to document the web interface and allow anyone to make an account and request?  Or do you prefer we point them to a person or a support page somewhere for now? 

Definitely getting to the point that lots of people need to make these.  I'd love it if we could do this in the API - but would need some sort of user auth.

**Comment by kunallillaney** [comment]
I did talk with Randal about this. There is a lot going on the admin side and the format in which we store data. Let us table this for now and once things have settled down we can look at the API capability.

**Comment by willgray** [comment]
Cool - so what should we tell people who want tokens?  Should there be
documentation to make an account and create tokens?  Should they ask
Kunal/Will/Alex?



Best,
Will

**Comment by kunallillaney** [comment]
With the new interface they will be able to register accounts on the admin interface. They can then create their own tokens. We should be out of the loop.

**Comment by kunallillaney** [comment]
kl-d7
