### ISSUE TITLE
simple catmaid not incrementing timeseries 

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#110]
http://openconnecto.me/ocp/ca/MC_Dual_170um_500um/005/xy/0/0,256/0,200/0/1/

http://openconnecto.me/ocp/ca/MC_Dual_170um_500um/005/xy/0/0,256/0,200/0/4000/

vs

http://openconnecto.me/ocp/catmaid/MC_Dual_170um_500um/005/xy/1/0/0_0_0.png

http://openconnecto.me/ocp/catmaid/MC_Dual_170um_500um/005/xy/4000/0/0_0_0.png

Unless I have the syntax wrong?

**Comment by kunallillaney** [comment]
This is now resolved.
