### ISSUE TITLE
pick better icons for timeseries buttons

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#112]
http://brainviz1.cs.jhu.edu/ocp/viz/freeman14/

I got the current set from https://fortawesome.github.io/Font-Awesome/icons/

The functionality is: 
Jump to beginning
Advance one timestep backwards
Advance one timestep forwards every xx seconds (user configurable) 
Stop advancing forwards
Advance one timestep forwards
Jump to end

I'm not sure that is well communicated. Thoughts?

**Comment by jovo** [comment]
maybe mouse over's can explain it?
the go to first & last was not obvious to me,
though maybe will be more obvious when the time shows up in the navbar

i'd also move these to the top left, next to all the other navigation buttons.
i'm not sure go to first & last are necessary or that useful.

in theory, a dropdown box containing all metadata info will list the boudaries, etc.

**Comment by alexbaden** [comment]
https://github.com/openconnectome/NeuroDataViz/issues/10
