### ISSUE TITLE
be able to dynamically upsample time-series data to look bigger

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#116]

**Comment by alexbaden** [comment]
So, I can upsample now. But it uses nearest neighbors, and isn't super awesome. 

The questions for you and @randalburns is:

1) how much do we want to upsample / zoom?
2) do we want to support upsample by 2 or by 4 in ocpviz regardless of the answer to 1? (of course if the answer to 1 is by 2-4 times, then...)

**Comment by jovo** [comment]
i think 2 and 4 in ocpviz is great.

On Thu, Aug 27, 2015 at 7:14 PM, Alex Baden <notifications@github.com>
wrote:

> So, I can upsample now. But it uses nearest neighbors, and isn't super
> awesome.
>
> The questions for you and @randalburns <https://github.com/randalburns>
> is:
>
> 1) how much do we want to upsample / zoom?
> 2) do we want to support upsample by 2 or by 4 in ocpviz regardless of the
> answer to 1? (of course if the answer to 1 is by 2-4 times, then...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/116#issuecomment-135580288>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York>

**Comment by alexbaden** [comment]
https://github.com/openconnectome/NeuroDataViz/issues/9
