### ISSUE TITLE
y coordinate lists 10.000000000001, maybe just 10 would be ok? or 10.0?

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#117]

**Comment by alexbaden** [comment]
I think we should round to nearest integer. Seems reasonable, right? You wouldn't want to get a cutout between two voxels anyway (OCP doesn't support that, I don't think).

**Comment by jovo** [comment]
agreed.

On Thu, Aug 27, 2015 at 6:42 PM, Alex Baden <notifications@github.com>
wrote:

> I think we should round to nearest integer. Seems reasonable, right? You
> wouldn't want to get a cutout between two voxels anyway (OCP doesn't
> support that, I don't think).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/117#issuecomment-135575662>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York>
