### ISSUE TITLE
new name?

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#120]
maybe NeuroImageViz or NeuroDataViz?

**Comment by alexbaden** [comment]
I decided to keep ocpviz until we either (1) change the name of the open-connectome software / repo (if we change the name) or (2) ocpviz works standalone w/out the open connectome stack on the same server.

**Comment by jovo** [comment]
ok, close this.

On Tue, Oct 6, 2015 at 11:40 AM, Alex Baden <notifications@github.com>
wrote:

> I decided to keep ocpviz until we either (1) change the name of the
> open-connectome software / repo (if we change the name) or (2) ocpviz works
> standalone w/out the open connectome stack on the same server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/120#issuecomment-145904582>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, medhacks <http://medhacks.org/>, calendar
<https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York>
