### ISSUE TITLE
parent

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#14]
for each project, i was thinking that perhaps we can have a field called 'parent',
which either points to another ocp token, or is root.
in particular, if the project is an annotation project, then its parent is the image data.
similarly, for a color corrected project.

for the raw images, its field is root.
this makes keeping track of things way easier, and doesn't require a full LIMS.

@willgray @randalburns @kunallillaney @alexbaden  - thoughts?

**Comment by willgray** [comment]
Isn't each annotation project already associated with an image project?

**Comment by jovo** [comment]
the new model is that there are only multichannel projects,
and they can be whatever they want, ie, no distinction between image
projects and annotation projects.

On Friday, March 27, 2015, William Gray <notifications@github.com> wrote:

>  Isn't each annotation project already associated with an image project?
>
> On Fri, Mar 27, 2015 at 4:53 PM, joshua vogelstein
> <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > for each project, i was thinking that perhaps we can have a field called
> 'parent',
> > which either points to another ocp token, or is root.
> > in particular, if the project is an annotation project, then its parent
> is the image data.
> > similarly, for a color corrected project.
> > for the raw images, its field is root.
> > this makes keeping track of things way easier, and doesn't require a
> full LIMS.
> > @willgray @randalburns @kunallillaney @alexbaden - thoughts?
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/openconnectome/open-connectome/issues/14
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/14#issuecomment-87096545>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>

**Comment by randalburns** [comment]
We have a default channel in each project.  This should suffice.  So every project can refer to "default".  I have aliased this as "parent" as well.
