### ISSUE TITLE
kasthuri catmaid broken

### ISSUE THREAD

**Issue by willgray** [openconnectome/open-connectome#141]
Most of these projects seem to not work.  Having a catmaid or leaflet project would aid my demos next week and also enable science.  :) openconnecto.me/catmaid/?dataview=13

**Comment by alexbaden** [comment]
We need to re-org the catmaid projects. Can you send me a list of tokens /
channel combinations for all the kasthuri data we want public? That info
isn't as readily apparent from current catmaid as it may seem.

**Comment by willgray** [comment]
Yea:

Image project is always kasthuri11cc, except where noted:

reference data:  ac3, ac4
annotations:  kat11segments, kat11synapses, kat11vesicles, kat11mito
3 cylinders:  kat11redcylinder, kat11greencylinder, kat11mojocylinder
--
low res data:  kasthuri14Maine  (standalone image project)
s1 column:  kasthuri14s1colEM linked to kasthuri14s1colANNO

   -
   -
   -

**Comment by alexbaden** [comment]
I believe I have fixed all the existing projects. Take a look and close if
I'm correct?

**Comment by willgray** [comment]
Thanks!  Looks good!
