### ISSUE TITLE
console docs issues

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#144]
they look great!
here are a bunch of tiny comments.

- "To upload an image volume" - please provide a link to the url that enables this
- python scripts are now called 'ndio' short for "neurodata ins & outs"
- cajal is all caps
- links to ndio and cajal at first mention
- "To upload annotation data" - provide a link
- "More information on general annotation upload and download is available here."  where is "here"? no link provided.
- "The Console" provide link please
- "The diagram below shows how the overall service is organized;" i think should end with a period. 
- replace all "OCP" with "NeuroData"?
- " annotation, ect." should say "etc."
- "etc." is also spelled wrong in the diagram
- i see, "etc." is spelled wrong in a bunch of places
- "Dataset Name" - give an example of a good name, like "bock11"
- "X, Y, Z Image Size"  - i don't understand what size means.  what unit are we in? please clarify units for each of these.  maybe even make a unit column to the right of  "Data Field"
- "Scaling Level" will also be unclear to the user, with respect to units, and what it means
- "To create a project navigate to the datasets drop down menu and select create dataset. "  from which url?
- "Public	Whether or not the template is viewable to the public."  encoded how? 0 vs 1? please clarity
- "Dataset	The dataset to be used by the project." what is entered here? the dataset name?
- "If you have not created a project yet follow this tutorial. "  which tutorial? the one immediately followed? the word "this" is often ambiguous.  maybe right "follow the below steps"?
- "A description of the channel, usually contains user description of the channel." seems a bit redundant? maybe i'm missing something?
- "Read Only" encoded by 0/1?
- "Resolution" what units?
- "The lowest pixel value (defaults to 0)"  i think this means "pixel *intensity* value"?

**Comment by Aeusman** [comment]
@kunallillaney This is pushed to latest ae-devel, @jovo please review.

**Comment by kunallillaney** [comment]
@Aeusman Merged with master. Let's meet sometime today or Monday to clear out some compile issues with the docs. I fixed some and would like to show you how to fix other's :)

**Comment by Aeusman** [comment]
@kunallillaney Finished, pushed to ae-devel

**Comment by kunallillaney** [comment]
awesome. thanks.

**Comment by jovo** [comment]
@kunallillaney - holler when it is deployed, and i'll check it over....

On Sat, Sep 19, 2015 at 2:05 PM, Kunal Lillaney <notifications@github.com>
wrote:

> awesome. thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/144#issuecomment-141694028>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
<https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
this update is pushed and can be accessed.

**Comment by jovo** [comment]
cool, i checked off all the items that seemed to be completed.
the others seem not yet completed?
