### ISSUE TITLE
why does this URL result in unknown exception in get cutout?

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#145]
http://openconnecto.me/ocp/ca/kharris15apical/hdf5/0/0,8192/0,8192/0,194/

**Comment by kunallillaney** [comment]
Because it is too big. You cannot except to do a 8kx8kx200 cutout.

**Comment by alexbaden** [comment]
Can I do a 8kx8kx100 cutout? 

Also, can we modify that error message so it tells the user the cutout size is too big?

**Comment by kunallillaney** [comment]
Can I please understand why are you trying to do these big cutouts? And no currently we have no error messages for these big cutouts.

**Comment by alexbaden** [comment]
It's a request from a user of that dataset.

**Comment by kunallillaney** [comment]
Her work flow is incorrect. The ideal size currently 512x512x16 or 1kx1kx16 cutouts.

**Comment by j6k4m8** [comment]
@alexbaden what's the target file format? hdf5?

**Comment by j6k4m8** [comment]
see [this script](https://gist.github.com/j6k4m8/467e4036635207aeb047) for a potential solution.
