### ISSUE TITLE
ocp fields

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#15]
http://w.ocp.me/images has a bunch of fields that i'd like in ocp.
i'm sure @kunallillaney working with the HBP people knows of others that they need/want.

**Comment by randalburns** [comment]
I would like to keep the open-connectome metadata limited to stuff that has physical meaning for the processing of images, volumes, annotations.  All of the experiment/subject specific metadata should go in the LIMS system.  Discuss.

**Comment by jovo** [comment]
i vote we test out COINS and see how easy it is to keep all the other meta
data in there? from the initial conversation with them, it seeemed that
COINS did not enable 'search' in any interesting ways.

@ebridge2 & @gkiar will be testing COINS during Q3, and they will report
back on this :)

On Tue, May 19, 2015 at 10:52 AM, Randal Burns <notifications@github.com>
wrote:

>  I would like to keep the open-connectome metadata limited to stuff that
> has physical meaning for the processing of images, volumes, annotations.
> All of the experiment/subject specific metadata should go in the LIMS
> system. Discuss.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/15#issuecomment-103534456>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
@jovo Can we close this or move this?

**Comment by jovo** [comment]
@willgray can you move this to the LIMS repo?

**Comment by j6k4m8** [comment]
[How to add data to LIMS](https://github.com/openconnectome/ndio-demos/blob/master/LIMS/Writing%20LIMS%20Data.ipynb)

[Me actually adding them to LIMS](https://github.com/openconnectome/LIMS-Scripts)

[Proof that this works](http://lims.neurodata.io/metadata/ocp/get/kasthuri11)
