### ISSUE TITLE
Add test for the new annjson service

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/open-connectome#158]
## Issues:
* Can you please add tests for the jsonann service you added? This will ensure that it won't be broken in the future when we make changes.
* Please add the call to the OCP documentation. We tend to fall behind on documentation, this ensure that we are update to date. 
* Run the pytest locally every time you want to merge something to ensure that everything is running fine at least OCP side.

**Comment by willgray** [comment]
On Mon, Oct 12, 2015 at 10:59 AM, Kunal Lillaney <notifications@github.com>
wrote:

> Issues:
>
>    - Can you please add tests for the jsonann service you added? This
>    will ensure that it won't be broken in the future when we make changes.
>    - Please add the call to the OCP documentation. We tend to fall behind
>    on documentation, this ensure that we are update to date.
>    - Run the pytest locally every time you want to merge something to
>    ensure that everything is running fine at least OCP side.
>
>
And CAJAL unit tests.  :)  [I realize here that we aren't impacting
CAJAL...but I'd like to make this accepted practice, because CAJAL is
locked in unless there's a new human interested in doing updates...so very
important that we don't break existing capabilities.]

Best,
Will

**Comment by alexbaden** [comment]
I ran both testing suites and they both passed. See my note in #156 .

**Comment by alexbaden** [comment]
It looks like the docs go here: http://docs.neurodata.io/open-connectome/api/ramon_api.html#annotation-service

but, the **options** for the current annotation service don't seem right. Where's *nodata* , for example?

As far as tests go, I am going to make a new ramon object, upload it, and then get the json info and check that it matches. This seems relatively redundant, but should cover the added functionality.

**Comment by kunallillaney** [comment]
I would look at test_json.py. Just make a copy of it and modify it for json interface. That would be the easiest.

**Comment by alexbaden** [comment]
Added a test. Pushed to ab-ocpviz. Docs issues handled in separate tickets ( #159, #160 )
