### ISSUE TITLE
Trouble deleting/recreating channel

### ISSUE THREAD

**Issue by willgray** [openconnectome/open-connectome#166]
Error is:  Failed to create channel. global name 'sql' is not defined

**Comment by alexbaden** [comment]
I've seen this before -- you probably have an illegal char in your chan name (perhaps "-")?

**Comment by kunallillaney** [comment]
The admin interface works as far as this functionality is concerned.

**Comment by willgray** [comment]
I agree.  But sometimes the process doesn't complete and recreating
channels fails.  I can show you.  After SFN!

Best,
Will

**Comment by randalburns** [comment]
I've seen this message.  I will fix.
I am working on backup/restore as we speak and I have a working backup
system ready to push.

On Fri, Oct 16, 2015 at 6:42 AM, William Gray <notifications@github.com>
wrote:

> I agree. But sometimes the process doesn't complete and recreating
> channels fails. I can show you. After SFN!
>
> Best,
> Will
>
> On Fri, Oct 16, 2015 at 7:54 AM, Kunal Lillaney <notifications@github.com>
> wrote:
>
> > The admin interface works as far as this functionality is concerned.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/open-connectome/issues/166#issuecomment-148696911
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/166#issuecomment-148706292>
> .
>



-- 
---

Randal Burns
Associate Professor
Department of Computer Science
The Johns Hopkins University

**Comment by kunallillaney** [comment]
@randalburns Ready to push to master?

**Comment by kunallillaney** [comment]
@willgray This is now fixed.
