### ISSUE TITLE
fix dns

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#179]
- [x] console.neurodata.io  --> http://openconnecto.me/ocp/ocp/accounts/login/
- [x] vx.neurodata.io --> http://128.220.176.8/data-analytics-website/Code/
- [x] gx.neurodata.io --> http://128.220.176.8/Graph-Explorer/shiny/
- [x] ix.neurodata.io --> viz

**Comment by alexbaden** [comment]
Done.
