### ISSUE TITLE
GUI & Django Model Bug Fixes

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/open-connectome#18]
Fix the the activation email module. The current setup is for django1.6 and broken because it is hard-coded to send all emails with link for dsp061.pha.jhu.edu. I think django1.7 does it differently(https://docs.djangoproject.com/en/dev/topics/email/)
Delete channel does not remove the tables. I have added a new method in OCPCADB called deleteOCPCAChannel() which needs to be called for channel deletes. I am calling this from views.py but seems to throw some error. ( the function in itself is tested and works fine)
Login Protect /channel and /token pages.
Non-owners of data public dataset should not be able to update it. 
Non public datasets are not available to super-users.
Lock the datatype for a channel type, image can only be uint8/uint16, annotation can be uint32/uint64 and so on.
Lock the propagation state to either propagated or non-propagated. It is set to propagating at start then it will never leave that state via the service.
If a user creates a project and set a default token, then the public value of token should be the same as that of the project, now all default tokens are public.
If a project is a public should all it's tokens be public? If no then we need to restrict this, issue 1 and this are related and have the same fix.
Ensure that there exits exactly one default channel.
Create a "link to existing channel" option in the GUI which does not create the channel tables.

**Comment by randalburns** [comment]
Enforce one default channel (when deleting default).
Radio button for default doesn't get preset.
