### ISSUE TITLE
zoom in for ROIs/annotations

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#180]
http://viz.neurodata.io/Fear199MaskLddmmABA//xy/0/9359/6104/500/

looks jenky.
perhaps downsampling using bilinear would work better?

@alexbaden @kunallillaney @mkazhdan

**Comment by jovo** [comment]
@alexbaden should we move this issue to ndv?

**Comment by alexbaden** [comment]
Nah, the code changes for downsampling will have to happen inside ocp. But
closing this one in favor of #184, which is more general.
