### ISSUE TITLE
dataset: description

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#185]
when i do this: http://openconnecto.me/ocp/ca/kasthuri11/info/

i get this:
```
"dataset": {
...
 "description": "kasthuri11", 
```

the documentation: http://docs.neurodata.io/open-connectome/sphinx/datamodel.html#dataset-attributes

however, does not list a "description" field, only a "name" field, which i don't see for the dataset.

do we have both a description and name field? can we? if not, can we clarify, cuz i'm confused.

**Comment by kunallillaney** [comment]
We have a field called description in the database which one can use to describe the description of the dataset. This field is a legacy field originally introduced to act as a very rudimentary information system for each dataset but never got used(and does not contain any meaningful data currently nor is used anywhere in the stack). The plan is to junk it once we have the LIMS system properly integrated into the stack and so we did not document it. I can add the documentation for this field if you like but it does nothing more than being a placeholder for now.

**Comment by kunallillaney** [comment]
I did add dataset name to both branches. We can close this.
