### ISSUE TITLE
auto-ingest has multiple channels

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#188]
a collaborator is trying to use auto-ingest, and has multi-channel data.
the current generatejson.py file only uses one channel in the example, 
but the function seems to support multichannel data.
so, can we make the example have 2 channels?

@kunallillaney

**Comment by Aeusman** [comment]
@jovo So I think the best way to do this without having to hard-code 3-4 channels worth of variables is to explain how they can add dictionary entries to the channels dictionary variable in the ingest doc. @kunallillaney sound good to you?

**Comment by jovo** [comment]
@Aeusman examples are king.  so i vote both :-)

**Comment by kunallillaney** [comment]
@Aeusman If is this done, then we can close it.

**Comment by Aeusman** [comment]
@kunallillaney @jovo I think this is done
