### ISSUE TITLE
generatejson error

### ISSUE THREAD

**Issue by owenrandlett** [openconnectome/open-connectome#189]
Hi - When I tried running the generatejson.py script (my version [generatejson.txt](https://github.com/openconnectome/open-connectome/files/78685/generatejson.txt), changed to '.txt' so that it would upload), I get some errors: 

 *File "generatejson.py", line 117
    print "Error in accessing JSON file, please double check name and path."
                                                                           ^
SyntaxError: Missing parentheses in call to 'print'*

If I add the relevant parentheses I get a different error relating to the Exception- 

 *File "generatejson.py", line 165
    except Exception, e:
                    ^
SyntaxError: invalid syntax*

Then if I comment out those lines I get a more complicated error: 

*Traceback (most recent call last):
  File "generatejson.py", line 173, in <module>
    main()
  File "generatejson.py", line 159, in main
    data = ocpJson(*complete_example)
  File "generatejson.py", line 33, in ocpJson
    for channel_name, value in channel_list.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Owens-MacBook-Air:autoingest owenrandlett$ python generatejson.py
Traceback (most recent call last):
  File "generatejson.py", line 173, in <module>
    main()
  File "generatejson.py", line 159, in main
    data = ocpJson(*complete_example)
  File "generatejson.py", line 33, in ocpJson
    for channel_name, value in channel_list.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'*

I am running python 3.5.1 on Mac OSX 10.10.5

Thanks for your help,

Owen

**Comment by j6k4m8** [comment]
To the best of my knowledge, this script is intended for Python 2.7. That would explain the `iteritems()` and `print` parens issues

**Comment by Aeusman** [comment]
@j6k4m8 is correct the script is intended for 2.7. If that fixes the problem @owenrandlett let me know and I'll close the issue.

**Comment by owenrandlett** [comment]
Indeed that did solve those issues - thanks! 

but, new error now -- 

*http://engertlab.fas.harvard.edu/~owen/NeuroData/Z-Brain/tERK001/
Error in accessing JSON file, please double check name and path.*

Could this perhaps this be related to

SITE_HOST = ""

Should this instead be set to something?

**Comment by Aeusman** [comment]
Yep! So SITE_HOST should be set to the server you are posting to, in this case openconnecto.me. The data URL is the link you just sent me.

**Comment by owenrandlett** [comment]
yep - that seems to have fixed it. Thanks!

**Comment by jovo** [comment]
@kunallillaney this thread.

**Comment by owenrandlett** [comment]
just a bit of user feedback -- I think it would be helpful if the fields that need to be filled out are all in one place and clearly marked as requiring input. Also, I think it should be mentioned somewhere in the doc that you need to run python 2.7. Perhaps this is all obvious to some, but it wasn't to me!

**Comment by kunallillaney** [comment]
@owenrandlett Thanks for your feedback. We have Incorporated that and updated our docs accordingly. Were you successful in getting your data into OCP? If not we can open another issue and see what is going wrong. Thanks.
