### ISSUE TITLE
take stock of hardware

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#191]
is this the only hardware that we have: http://w.ocp.me/private:hardware:cis

if not, can it please be updated ASAP, i need to know for some stuff grant immediately.
in particular, we have not very much time to spend on **$60k**, so we need to decide what to spend it on,
so we need to know what we have.
and we need to act *fast*, or we will lose the money!

please include datascope nodes, bg1, bg1dev, awesome, everything we have.
please be sure to include how much *storage* we have for each of these nodes, 
and how they are connected.

ideally, in paragraph form, such as the attached pdf, but specifically for *our captive* resources, not generic JHU resources.  

[resources.pdf](https://github.com/openconnectome/open-connectome/files/87346/resources.pdf)

@Aeusman @kunallillaney @willgray @alexbaden @perlman

**Comment by Aeusman** [comment]
So I don't have an up to date knowledge on this, this may be a @kunallillaney question. Most up to date knowledge I have is in automated i2g framework paper.

**Comment by willgray** [comment]
@alexbaden knows what we bought for compute.

**Comment by alexbaden** [comment]
See the file I just made in datasets. It has all systems from CIS listed, specs are incomplete. I'll finish that up shortly. I also made an issue over there.

**Comment by kunallillaney** [comment]
@alexbaden @jovo Is this done?

**Comment by jovo** [comment]
nope, but it is close.
@icoming still waiting on awesomer specs.
@disa-mhembere put them somewhere, but not in the table.

**Comment by icoming** [comment]
awesomer has 4 Intel Xeon processors, each of which has 12 CPU cores, and 1TB of DDR3 RAM. It also has 24 SSDs with total capacity of 9.4TB.

Is this sufficient?

**Comment by disa-mhembere** [comment]
This is what I used for awesome:

`4x Intel(R) Xeon(R) CPU E7-4860 v2 @ 2.60GHz
Description: Ubuntu 14.04.3 LTS
RAM: 1 TB
Storage: 24 X 400GB SSDs = 9.4 TB, 256 GB mounted on home`

**Comment by jovo** [comment]
+`
