### ISSUE TITLE
clarify what a 32bit image is

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#195]
http://docs.neurodata.io/open-connectome/api/ocp_types.html

Say I have an image dataset and mark it w/ datatype 32-bit integer. Does that mean we're interpreting my image dataset as RGBA data, or "32-bit grayscale" (which isn't actually a thing, but neither is 16-bit grayscale, and who says what things are things, anyway?)

My question really is, if I get a 32-bit image channel and look at some voxel v, should I interpret v as:

[ first 8 bits = R] [second 8 bits = G] [third 8 bits = B] [fourth 8 bits = A]

or

[32 bits = intensity value]

( @jovo @randalburns )

**Comment by kunallillaney** [comment]
[ first 8 bits = R] [second 8 bits = G] [third 8 bits = B] [fourth 8 bits = A]
We are treating image + 32 bit as RGBA data.

**Comment by jovo** [comment]
i see.
@Aeusman can you fix the docs to clarify?
