### ISSUE TITLE
CAJAL test failures/warnings

### ISSUE THREAD

**Issue by willgray** [openconnectome/open-connectome#205]
I did the following:

- Downloaded CAJAL master
- Added toolbox to path
- Changed server to http://brainviz1.cs.jhu.edu on line 17 of testOCP.m
- ran 'testOCP.m'

The following test failures exist.  Recommend addressing prior to merge.

@kunallillaney @alexbaden @jovo @j6k4m8 @randalburns 

~~~
Starting test run with 67 test cases.
....F...............
..........F.........
FWarning: At least 1 of the provided global coordinates are outside the local volume. 
> In RAMONVolume/global2Local (line 236)
  In testOCP>testCutoutvsDenseSingleSlice (line 1978)
  In FunctionHandleTestCase/runTestCase (line 112)
  In TestCase/run (line 74)
  In TestSuite/run (line 85)
  In initTestSuite (line 56)
  In testOCP (line 21) 
F..................
.......
FAILED in 374.158 seconds.

===== Test Case Failure =====
Location: /Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m
Name:     testUploadDownloadProbMapCutout

/Users/graywr1/Downloads/CAJAL-test/api/matlab/ocp/OCP.m at line 1905
/Users/graywr1/Downloads/CAJAL-test/api/matlab/ocp/OCP.m at line 1232
/Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m at line 254

The class eRAMONChannelType has no property or method named 'probmap'.


===== Test Case Failure =====
Location: /Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m
Name:     testAnnotationSlice

/Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m at line 1383

Inputs are not equal.

First input:
[880x1 double]

Second input:
[725x1 double]


===== Test Case Failure =====
Location: /Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m
Name:     testCutoutvsDense

/Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m at line 1890

Inputs are not equal.

First input:
     0

Second input:
     1


===== Test Case Failure =====
Location: /Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m
Name:     testCutoutvsDenseSingleSlice

/Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m at line 1979

Attempted to access s1.data(50,20,2); index out of bounds because size(s1.data)=[100,80,1].
~~~

**Comment by alexbaden** [comment]
Can you run against openconnecto.me as well?

**Comment by alexbaden** [comment]
`probmap` was deprecated, and CAJAL was never changed. You can still write probmap data, just use float32 and image instead. If that needs to be updated in CAJAL, I can look at it later. 

On the second failure, notice the following:

http://brainviz1.cs.jhu.edu/ocp/ca/kasthuri11/info/ shows kasthuri11 as being:
```
            "0": [
                21504, 
                26624, 
                1851
```
whereas ocp shows:
```
            "0": [
                21504, 
                26624, 
                1850
            ], 
```

I may have messed up transcribing kasthuri11 over. There are also test failures using CAJAL against the current master. That's the nature of a lot of these CAJAL tests (they don't transfer between servers well, you have to blank the DBs, etc). So, I'd be curious to see how CAJAL does against the current master.

**Comment by willgray** [comment]
Hey - thanks for looking into this - patching probmap is probably a good idea bc of existing downstream usage.

Here's what I get when I run same test suite on openconnecto.me.  To my knowledge this is a new bug, and possibly related to databases not being cleared.

~~~

>> testOCP
Starting test run with 67 test cases.
....................
....................
....................
..F....
FAILED in 512.043 seconds.

===== Test Case Failure =====
Location: /Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m
Name:     testIDFilterSlice

/Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m at line 2896

Inputs are not equal.

First input:
     2

Second input:
     3

~~~

**Comment by willgray** [comment]
...in any case, this is a different failure than the ones I sent previously.  :)

**Comment by kunallillaney** [comment]
@willgray Are we good to go?

**Comment by willgray** [comment]
I think all of these need to be fixed before we push.  I haven't run any subsystem or deploy tests, so we are counting on this stuff to work.

**Comment by alexbaden** [comment]
I'm having a lot of trouble replicating the bugs above (locally, on dsp029, on brainviz, etc). I think, because the unit tests rely heavily on kasthuri11, that we should try the following:

Merge ndio into master and deploy on some agreed date. After deployment I'll immediately run tests and see what tests fail. From there we can either update CAJAL and/or update the datascopes as necessary. It will result in some "downtime", but it's the best way to make sure everyone is working off the same page. Every time I try CAJAL on a different server I get a different result!

**Comment by willgray** [comment]
i don't hate this idea if you are committed to fixing things that are broken in short order?  worst case, these bugs suggest that data isn't being posted or returned right, so could be a huge deal.  But could be a server thing as you point out, and is probably a fairly quick adjustment.  I don't have much bandwidth on my end, but will do what I can.

**Comment by alexbaden** [comment]
Yeah, we can work out the scheduling details offline (maybe in slack?).

**Comment by willgray** [comment]
It works!!!

First test failure is expected and should probably be deprecated.

```
Starting test run with 67 test cases.
F...................
....................
....................
.......
FAILED in 2994.733 seconds.

===== Test Case Failure =====
Location: /Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m
Name:     testInit

/Users/graywr1/Downloads/CAJAL-test/test/matlab/api/testOCP.m at line 49

Expected exception "OCP:ServerConnFail", but none thrown.
```

**Comment by jovo** [comment]
will is SOOO :gruntled: right now :+1:
