### ISSUE TITLE
Fix test_stats in master.

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/open-connectome#207]
@alexbaden I think there is something fundamentally wrong with your test_stats. It seems to pass even when the back-end is throwing an error. This is not ideal because it gives a false sense that the test is passing and the service is running.

**Comment by alexbaden** [comment]
Stats was not included in `settings.py` (the viz url that was previously set was also missing, which broke old ocpviz redirects). I set those and restarted supervisor, but the celery queue still isn't registered stats tasks, I think. 

I also can't replicate the bug where the stats test passes but doesn't actually generate the histogram. Can you provide instructions for replicating?

**Comment by kunallillaney** [comment]
The settings file was copied from the settings.example file. Was it not in there? 
To replicate the bug, try the new microns branch and run your tests without any celery processes or settings.

**Comment by alexbaden** [comment]
I see, I thought this was on the current master. Let me get stats working on current master, first, then I'll look at microns.

**Comment by kunallillaney** [comment]
It is also happens on the current master.

**Comment by alexbaden** [comment]
Steps to reproduce...

**Comment by kunallillaney** [comment]
I pulled the current master on dsp's. The settings file the same as settings.example, copied the celery conf file and ran it. Tested this on the django dev server.

**Comment by alexbaden** [comment]
All stats tests pass on current master. I don't see any errors in the dev server when running them, either. Closing this in favor of #208 which will cover tests on the microns branch.
