### ISSUE TITLE
Probability overlays in browser broken

### ISSUE THREAD

**Issue by willgray** [openconnectome/open-connectome#30]
@randalburns @kunallillaney:  Did interface for probability overlays change?  They quit working for me (actually about a month ago...)

Doesn't work (prob32)
http://openconnecto.me/ocp/overlay/0.7/kasthuri11_ac3_membranes/xy/1/5472,6496/8712,9736/1005/  

Does work (anno32)
http://openconnecto.me/ocp/overlay/0.7/kasthuri11_ac3_synapseTruth/xy/1/5472,6496/8712,9736/1005/

-----  500 error, not particularly informative to me -----

HTTPError at /overlay/0.7/kasthuri11_ac3_membranes/xy/1/5472,6496/8712,9736/1005/
HTTP Error 500: INTERNAL SERVER ERROR
Request Method:	GET
Request URL:	http://openconnecto.me/ocp/overlay/0.7/kasthuri11_ac3_membranes/xy/1/5472,6496/8712,9736/1005/
Django Version:	1.6.1
Exception Type:	HTTPError
Exception Value:	
HTTP Error 500: INTERNAL SERVER ERROR
Exception Location:	/usr/local/lib/python2.7/urllib2.py in http_error_default, line 527
Python Executable:	/usr/share/ocp/virtualenvs/ocp/bin/uwsgi
Python Version:	2.7.3
Python Path:	
['.',
 '',
 '/usr/share/ocp/virtualenvs/ocp/lib/python27.zip',
 '/usr/share/ocp/virtualenvs/ocp/lib/python2.7',
 '/usr/share/ocp/virtualenvs/ocp/lib/python2.7/plat-linux2',
 '/usr/share/ocp/virtualenvs/ocp/lib/python2.7/lib-tk',
 '/usr/share/ocp/virtualenvs/ocp/lib/python2.7/lib-old',
 '/usr/share/ocp/virtualenvs/ocp/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/share/ocp/virtualenvs/ocp/lib/python2.7/site-packages',
 '/usr/share/ocp/open-connectome/django',
 '/usr/share/ocp/open-connectome/util',
 '/usr/share/ocp/open-connectome/ocpca',
 '/usr/share/ocp/open-connectome/ocplib']
Server time:	Tue, 28 Apr 2015 00:17:16 -0400

**Comment by kunallillaney** [comment]
@willgray So I am not sure if we are going to be supporting overlays in the new branch. I need to talk with Randal on how this will be supported and what kind of format are we looking at.

**Comment by willgray** [comment]
Cool.  I vote for them, for whatever that's worth.  Mostly letting you know
they don't work, in case you didn't...

Best,
Will

**Comment by jovo** [comment]
what are the implications of not supporting overlays?

On Tuesday, April 28, 2015, William Gray <notifications@github.com> wrote:

>  Cool. I vote for them, for whatever that's worth. Mostly letting you know
> they don't work, in case you didn't...
>
> Best,
> Will
>
> On Tue, Apr 28, 2015 at 7:12 PM, Kunal L <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @willgray <https://github.com/willgray> So I am not sure if we are going
> > to be supporting overlays in the new branch. I need to talk with Randal
> on
> > how this will be supported and what kind of format are we looking at.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/open-connectome/issues/30#issuecomment-97258095
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/30#issuecomment-97259231>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by randalburns** [comment]
Overlays exist in the new branch and have been refactored to support channels.  They need to be documented/redocumented.  See me and I will work it with you or give my two channels and I will send you an example overlay URL.

**Comment by kunallillaney** [comment]
@randalburns @willgray Is this fixed now? If no then I can work with @willgray on it.
