### ISSUE TITLE
Throw a more specific error if the HDF5 dataset name does not match the channel name when posting data

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#35]
It doesn't seem like it would be too hard... just add a check to see if the h5py.get call returns None, and then throw an error. I'm happy to do it. @randalburns @kunallillaney, what say you?

**Comment by randalburns** [comment]
These types of changes you can make as you see fit.  Let me know if you want me to do it.  There's many patterns that show how to add a logger.error and throw OCPCAError
