### ISSUE TITLE
propagation service not updated to use new schema? 

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#37]
See ocpcarest line 1444. Looks like it's trying to pull getPropagate values from the project instead of the channel.

**Comment by alexbaden** [comment]
I think I fixed this here ( https://github.com/openconnectome/open-connectome/commit/ede55ff412c976cecb4d8420d03c2a8203058365 ). Can someone ( @kunallillaney , @randalburns ) confirm? 

Might be worth writing a test for this...

**Comment by kunallillaney** [comment]
I will look into this and will add a test. There are some more changes which need to go here.

**Comment by kunallillaney** [comment]
This is now fixed. And there is a new test for it as well. Will be pushed shortly.
