### ISSUE TITLE
refactor the HDF5 service to produce both DATATYPE and DBTYPE

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#38]
Right now it produces DATATYPE, which contains one of {image, annotation, probmap, etc}. I'd like to rename that DBTYPE and add DATATYPE, which contains {uint8, uint16, uint32, etc}. We could probably engineer a solution to pull the DATATYPE from the CUTOUT, but this is a more general way to do it.

**Comment by alexbaden** [comment]
I changed this so I can make progress on CAJAL right now. Easy enough to refactor if we decide something else.

**Comment by randalburns** [comment]
OK, we decided on naming these "channel type" and and "data type"  This is consistent with the ocpcaprojects implementation with has channel_type and channel_datatype

**Comment by alexbaden** [comment]
Need to rename this to CHANNELTYPE in my branch ( ab-cajal-d7 )

**Comment by kunallillaney** [comment]
@alexbaden @randalburns Have we reached a consensus on this? Let me know the final format for both POST and GET(ideally the same) and I will ensure that it is the same.

**Comment by kunallillaney** [comment]
Done.
