### ISSUE TITLE
POSTing HDF5 annotations and probability maps doesn't seem to work on the new branch

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#40]
The file appears to post fine, but when I download the cutout in HDF5 format using the same URL, I get a file of all "0s".

**Comment by randalburns** [comment]
Without looking at it, I suspect that your project has either (1) a resolution set above the posted resolution or (2) has PROPAGATED=False.
Both cause specific problems that I can describe and we should document.  See me this afternoon.

@Kunal: I feel like this propagated flag is a user disaster.  We should discuss.

  randal

**Comment by willgray** [comment]
yea, propagated is weird from a user perspective.  agree that in the limit
everything should be propagated, but we've only needed ~1% of our anno
projects propagated in practice - only the stuff that goes into a paper.

Adds a lot of complexity.

Best,
Will

**Comment by alexbaden** [comment]
It was a propagation issue. I am closing this, but we should remember to revisit propagation next week.

**Comment by kunallillaney** [comment]
@randalburns Just saw this. Propagation has an issue if it gets stuck in 1. I will see if I can do better exception handling and turn it back to non-propagated if it fails
