### ISSUE TITLE
is there any 'easy' way to get a list of all projects with at least 1 public token?

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#41]
i am thinking it would be great to automatically generate a table from projinfo (for public projects) that had fields like:

  - dataset name
  - species
  - xyz resolution
  - xyz pixels
  - image modality
  - data type
  
@kunallillaney @randalburns @alexbaden @willgray how hard is that to make?

**Comment by randalburns** [comment]
It's easy-ish.  First you call: 
  http://openconnecto.me/ocp/ca/public_tokens/
returns a JSON list of public tokens.
Then you call:
  http://openconnecto.me/ocp/ca/takemura13/info/
on each token -- takemura13 in this case.

**Comment by jovo** [comment]
yah, but the public tokens are weird.  there are like 10 for nick weiler's
data, and then none for other data, like the nematodes or drosophila data,
even though they are public.

so, i want all public 'dataset' tokens, where nick's data counts as 1
dataset.

On Mon, May 18, 2015 at 5:30 PM, Randal Burns <notifications@github.com>
wrote:

>  It's easy-ish. First you call:
> http://openconnecto.me/ocp/ca/public_tokens/
> returns a JSON list of public tokens.
> Then you call:
> http://openconnecto.me/ocp/ca/takemura13/info/
> on each token -- takemura13 in this case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/41#issuecomment-103218163>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by randalburns** [comment]
Agreed, and the annotations for takemura are not public.

Kunal, can you please audit the public data sets when you return
to make sure they reflect what’s on the Website.

  randal

**Comment by kunallillaney** [comment]
@jovo Can you please look at the datamap we have and let me know which ones are public? I don't want to make the private ones public as well.

**Comment by jovo** [comment]
@kunallillaney is this one up to date:
is this one up to date: http://w.ocp.me/private:datamap

**Comment by kunallillaney** [comment]
@jovo yes that I know of. It does not have tokens for the data recently ingested on the new branch which is private anyways and not accessible from the main servers. Send me an email with all the tokens and I will update them to be public.

**Comment by jovo** [comment]
@kunallillaney do you want (1) project names, (2) datasets, and/or (3) tokens that are public.
i guess because individual tokens can be public/private, i should give you all the tokens?

@willgray can you confirm these?
- all kasthuri tokens are public (except rhoana)
- all kharris15
- freeman14
- bock11
- all mitra tokens
- flyemanno
- takemura13
- all the nick weiler ones (eg, Ex14R58)
- cardona ones (not the cc ones)

**Comment by kunallillaney** [comment]
I want token names which should be public. Datasets is too general since we have datasets with tokens which are not public.

**Comment by alexbaden** [comment]
kharris should remain private until accepted, no?


Alex

**Comment by willgray** [comment]
i haven't heard a definitive answer from bobby either.  My belief is the
fly stuff is public, but I didn't negotiate those.

Kasthuri data (all res), bock11 data, and Nick's tokens are public and
should remain so.

Best,
Will

**Comment by jovo** [comment]
i guess i'm confused what "public" means?

eg, for bobby's data, catmaid uses various annotation tokens, so in a
certain sense, they must be public?

you are right, kharris is all private still.

On Mon, May 25, 2015 at 6:39 PM, William Gray <notifications@github.com>
wrote:

>  i haven't heard a definitive answer from bobby either. My belief is the
> fly stuff is public, but I didn't negotiate those.
>
> Kasthuri data (all res), bock11 data, and Nick's tokens are public and
> should remain so.
>
> Best,
> Will
>
> On Mon, May 25, 2015 at 6:36 PM, Alex Baden <notifications@github.com>
> wrote:
>
>
> > kharris should remain private until accepted, no?
> >
> >
> > Alex
> > On Mon, May 25, 2015 at 18:34 Kunal L <notifications@github.com> wrote:
> >
> > > I want token names which should be public. Datasets is too general
> since
> > > we have datasets with tokens which are not public.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105327998
> > >
> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105328709
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105328886>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
we made catmaid projects for bobby, but there was sensitivity until
publication.  so in some sense hiding in plain sight, but no one actually
knows how/what to do to access what's there.  If we're gonna advertise it
as a ref example we should ask (again)


Best,
Will

On Mon, May 25, 2015 at 6:48 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
@willgray - can you give kunal the real list then, i fucked it up :)

On Mon, May 25, 2015 at 6:52 PM, William Gray <notifications@github.com>
wrote:

>  we made catmaid projects for bobby, but there was sensitivity until
> publication. so in some sense hiding in plain sight, but no one actually
> knows how/what to do to access what's there. If we're gonna advertise it
> as a ref example we should ask (again)
>
>
> Best,
> Will
>
>
> On Mon, May 25, 2015 at 6:48 PM, joshua vogelstein <
> notifications@github.com
> > wrote:
>
> > i guess i'm confused what "public" means?
> >
> > eg, for bobby's data, catmaid uses various annotation tokens, so in a
> > certain sense, they must be public?
> >
> > you are right, kharris is all private still.
> >
> > On Mon, May 25, 2015 at 6:39 PM, William Gray <notifications@github.com>
> > wrote:
> >
> > > i haven't heard a definitive answer from bobby either. My belief is the
> > > fly stuff is public, but I didn't negotiate those.
> > >
> > > Kasthuri data (all res), bock11 data, and Nick's tokens are public and
> > > should remain so.
> > >
> > > Best,
> > > Will
> > >
> > > On Mon, May 25, 2015 at 6:36 PM, Alex Baden <notifications@github.com>
> > > wrote:
> > >
> > >
> > > > kharris should remain private until accepted, no?
> > > >
> > > >
> > > > Alex
> > > > On Mon, May 25, 2015 at 18:34 Kunal L <notifications@github.com>
> > wrote:
> > > >
> > > > > I want token names which should be public. Datasets is too general
> > > since
> > > > > we have datasets with tokens which are not public.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105327998
> > > > >
> > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105328709
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105328886
> > >
> > > .
> > >
> >
> >
> >
> > --
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> >
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105329869
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105330036>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by alexbaden** [comment]
Public tokens show up in the list public API call.

Catmaid projects can be public or private regardless of the token status.

ocpviz will probably inherit from the token, unclear what that will mean.


Alex

**Comment by kunallillaney** [comment]
Can we shelve this for now until we have a list?

**Comment by jovo** [comment]
will - can u give kunal the final list?

On Tuesday, May 26, 2015, Kunal L <notifications@github.com> wrote:

>  Can we shelve this for now until we have a list?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/41#issuecomment-105675035>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
any status update on this?

**Comment by jovo** [comment]
will is on vaca.
he'll get back next week.
i think everything that is in catmaid in public is open, and nothing else.

On Tue, Jun 2, 2015 at 9:41 PM, Kunal L <notifications@github.com> wrote:

>  any status update on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/41#issuecomment-108155591>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
@kunallillaney - how can i make tokens public in the console?  I'm ready.

Or do you want to do it?

**Comment by kunallillaney** [comment]
@willgray this is done. Let me know if you have any issues.

**Comment by willgray** [comment]
This is indeed done.  Interface worked great.  All Kasthuri tokens are
public.  http://dsp061.pha.jhu.edu/ocp/ca/public_tokens/
