### ISSUE TITLE
syncdb/migrate issues (must run twice)

### ISSUE THREAD

**Issue by randalburns** [openconnectome/open-connectome#46]
when creating a new database, syncdb needs to be run twice to create the database.  why?

**Comment by alexbaden** [comment]
You might want to delete all migrations and make new migrations starting
from zero on a good copy of the branch. I can demo / try it.

**Comment by randalburns** [comment]
There is no more syncdb.  This must be done with migrations.  The problem is that one can't just start the entire database de novo.  The following sequence is required and must be put in our instructions.

python manage.py makemigrations ocpuser     
python manage.py migrate

This creates an order so that all the auth tables are created first and then the ocpuser models are defined after the auth tables are created.
