### ISSUE TITLE
Local Django Server CSRF Error

### ISSUE THREAD

**Issue by Aeusman** [openconnectome/open-connectome#48]
I have created a local django server (open-connectome) and the server passes all tests (from py.test). However when attempting to log into the server (/accounts/login/) I am getting a "CSRF verification failed" error.

**Comment by kunallillaney** [comment]
@randalburns There seems to be a CSRF error in django even when it is commented out.

**Comment by j6k4m8** [comment]
Not sure if you're still having this problem, but adding the request token (via Django templating, `{% csrf_token %}` inside the `<form>`) fixes this problem in the newer Django versions, if my memory serves correctly.

**Comment by kunallillaney** [comment]
@j6k4m8 Yeah but we have the csrf options commented out in the settings file. that should remove this.

**Comment by kunallillaney** [comment]
this seems to not have surfaced.
