### ISSUE TITLE
Why is there both a database host and a kvserver host?

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#55]
What is the difference between the two? 

@kunallillaney @randalburns

**Comment by kunallillaney** [comment]
Database host is the server where the database is located for MySQL. KVServer is a Cassandra artifact where we can choose some servers in the cluster to be a key server.

**Comment by alexbaden** [comment]
Seems confusing to have both in the channel creation form.

**Comment by kunallillaney** [comment]
There are both only present in the project creation form not the channel creation one. I checked again.

**Comment by alexbaden** [comment]
Sorry, that's what I meant.

**Comment by kunallillaney** [comment]
Yes but I don't think we can get around it without redesigning the UI. This was stop-gap measure we introduced when Randal wrote the IO layer for Riak and Cassandra. Remember both of them are different things and thus cannot be put in the same field. We can make this dynamic depending on the engine chosen by the user but that is more work in the UI.
