### ISSUE TITLE
What is the syntax for accessing an xy cutout of time series data in the new branch?

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#56]
@kunallillaney @randalburns

**Comment by kunallillaney** [comment]
token/channel/slice/resolution/time/x,x/y,y/z/

**Comment by alexbaden** [comment]
Not sure this is working:
```
http://brainviz1.cs.jhu.edu/ocp/ca/freeman14/default/xy/0/15,16/500,1000/0,500/50/
Illegal image arguments=0/15,16/500,1000/0,500/50/. Error='NoneType' object has no attribute 'group'
```

Same thing with just /15/, and with hdf5 instead of the xy service. Something I'm doing wrong?

**Comment by kunallillaney** [comment]
Sorry about that. The one I mentioned is the old one. The new one is token/channel/slice/resolution/x,x/y,y/z/time/. For example, http://braindump1.cs.jhu.edu:8000/ca/kasthuri11/time1/xy/0/500,1000/0,500/50/15/. This query fails for you because your project has 2 default channels. This is a bug which Randal has not been able to eliminate.

**Comment by kunallillaney** [comment]
Is this resolved?

**Comment by alexbaden** [comment]
I don't think so:

http://brainviz1.cs.jhu.edu/ocp/ca/freeman14/default/xy/0/500,1000/500,1000/20/15,15/

http://brainviz1.cs.jhu.edu/ocp/ca/freeman14/default/xy/0/500,1000/500,1000/20/15,16/

Looks like the regex in imgslice isn't matching.


Alex

**Comment by kunallillaney** [comment]
/kasthuri11/time1/xy/0/500,1000/0,500/50/15/. Follow the syntax. It is only 15 not 15,15

**Comment by alexbaden** [comment]
http://brainviz1.cs.jhu.edu/ocp/ca/freeman14/default/xy/0/500,1000/500,1000/20/15/

**Comment by kunallillaney** [comment]
Remove the 2 default channels.

**Comment by alexbaden** [comment]
I did that, looks like there's a different issue:
```
Traceback (most recent call last):
  File "/Users/abaden/Projects/open-connectome/django/ocpca/views.py", line 52, in cutout
    return django.http.HttpResponse(ocpcarest.getCutout(webargs), content_type="image/png" )
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 688, in getCutout
    return selectService ( service, webargs, proj, db )
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 523, in selectService
    return imgPNG(proj, webargs, imgSlice (webargs, proj, db))
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 364, in imgSlice
    cb = cutout(cutoutargs + (filter_args if filter_args else ""), ch, proj, db)
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcarest.py", line 78, in cutout
    cube = db.timecutout(ch, corner, dim, resolution, timerange)
  File "/Users/abaden/Projects/open-connectome/ocpca/ocpcadb.py", line 1101, in timecutout
    outcube = Cube.getCube([xnumcubes*xcubedim,ynumcubes*ycubedim,znumcubes*zcubedim], ch.getChannelType(), ch.getDataType(), timerange=timerange)
  File "/Users/abaden/Projects/open-connectome/ocpca/cube.py", line 118, in getCube
    return timecube.TimeCube16(cubedim, timerange)
```

When I looked in timecube.py, the TimeCube16 definition doesn't seem to match TimeCube8. Maybe it didn't get copied over correctly?

**Comment by kunallillaney** [comment]
Fixed and pushed to kl-d7.
