### ISSUE TITLE
graphml is not defined

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#58]
NameError at /ocp/accounts/login/
name 'graphml' is not defined

see https://github.com/openconnectome/open-connectome/commit/4719ce21a513bbb4cc7381afeb95b228e5515d89

I ended up adding quotes around it and it works. 

there were two other syntax errors -- I didn't actually fix them, just commented them out, so I might have broken something. In python you can't write something like
```
test = # comment
``` 
because it expects something after test = and doesn't parse the comment. Stupid, but commenting out the full line seems to do the trick.

**Comment by kunallillaney** [comment]
@alexbaden  This does not seem to be a problem after your changes now. I can deploy this branch.

**Comment by Aeusman** [comment]
Sorry, missed those on my scan through before commit, will edit/update as I work on ramon graphGen today

**Comment by Aeusman** [comment]
Issue should be fixed in latest commit.
