### ISSUE TITLE
add timeseries support to simplecatmaid 

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#59]
I'd like to get this in by early next week. I've integrated some controls into ocpviz, but can't test it. Tried deploying the tilecache, but that doesn't work too, and I can't run it on my mac b/c of directory issues or debug it on brainviz because port 8080 is blocked (thanks JHU). There's a different issue for that one...

I can do this if you want. Seems pretty simple, shouldn't take me too long. Just re-assign to me.

**Comment by kunallillaney** [comment]
Done. Let me know if there are any issues.
