### ISSUE TITLE
Modify `STATIC_ROOT` et al during Auto-Setup

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/open-connectome#64]
These items should be modified to be prefix'd with `pwd` (or `os.path.dirname(os.path.realpath(__file__))`, if that's easier) when you run the auto-setup script

Not necessarily all-inclusive list:

- [ ] `STATIC_ROOT`
- [ ] `STATIC_URL`
- [ ] `STATICFILES_DIRS`
- [ ] `TEMPLATE_DIRS`

**Comment by kunallillaney** [comment]
@Aeusman This is an enhancement we came across today. This is optional. :)

**Comment by kunallillaney** [comment]
Moving to relative paths.
