### ISSUE TITLE
Modify FORCE_SCRIPT_NAME in auto-setup script

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/open-connectome#65]
Should be `/` locally, `ocp` elsewhere

**Comment by kunallillaney** [comment]
@j6k4m8 @Aeusman this is bit difficult to do and should be really /ocp at all times. We can talk more about this.

**Comment by Aeusman** [comment]
We are keeping this as /ocp correct? If so close this?

**Comment by kunallillaney** [comment]
Yes.
