### ISSUE TITLE
timeseries16 windowing doesn't work in simplecatmaid

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/open-connectome#75]
The problem seems to be on line 297 of ocpcarest.py:

```
if ch.getChannelType() in ocpcaproj.IMAGE_CHANNELS and ch.getDataType() in ocpcapro     j.DTYPE_uint16:
```
timeseries16 isn't in ocpcaproj.IMAGE_CHANNELS. Seems like a quick fix is to add timeseries to the list of image channels? Not sure if that has unintended consequences ( @randalburns @kunallillaney )

**Comment by kunallillaney** [comment]
pushed to master.
