### ISSUE TITLE
update console docs to be in the open-connectome docs

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#81]
@kunallillaney can help

**Comment by jovo** [comment]
@kunallillaney if this is redundant, close it.

**Comment by jovo** [comment]
great! same question :)

On Thu, Sep 10, 2015 at 3:51 PM, Kunal Lillaney <notifications@github.com>
wrote:

> Closed #81 <https://github.com/openconnectome/open-connectome/issues/81>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/81#event-406377042>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
<https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
getting pushed. Am with @Aeusman who is wrapping this up. :)

**Comment by jovo** [comment]
yay!!! thanks @aeusman & @kunallilaney!

On Thu, Sep 10, 2015 at 3:54 PM, Kunal Lillaney <notifications@github.com>
wrote:

> getting pushed. Am with @Aeusman <https://github.com/Aeusman> who is
> wrapping this up. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/81#issuecomment-139362857>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
<https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
http://docs.neurodata.io/open-connectome/sphinx/console.html
