### ISSUE TITLE
spec details

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#83]
the details of the specs for how data should be organized when ingesting (with or without the service) must be clear.  
in particular, details for how to *check* whether the data are to spec should be included.

some of our friends have tried to follow the 'spec' we've given them, but failed, for various reasons.  if they fail, it should never be our fault. 

in the not too distant future, it occurs to me that the right way to do this would be to provide a script that they run locally that cross-checks the json file with the images.

@randalburns @kunallillaney @Aeusman @j6k4m8

**Comment by kunallillaney** [comment]
Now in HBP. Closed a similar issue.
