### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#84]
each function should have:
 - a 1 sentence description of what it does.
 - an example of using it (and its expected results)

**Comment by kunallillaney** [comment]
There is a single line called synopsis which explains what that does. I will add single line examples.

**Comment by jovo** [comment]
ah, i see.
i guess what i mean is,
if somebody doesn't know what 'propagate' means, the existing 1-sentence
summary doesn't help.
this applies to most of the commands, afaict.

for example, in http://mri.ocp.me/open-connectome/api/overlay_api.html
"Get a XY Slice Cutout" doesn't clarify to most people.

something like:

"Download a single image of a specified canonical plane (XY, XZ, or YZ),
and specified channels, resolution, and bounds. Your browser can load these
images."

would be good at the top of the page.

something like that for each of the .html pages (not subsections), would be
awesome.



On Sun, Aug 9, 2015 at 12:52 PM, Kunal Lillaney <notifications@github.com>
wrote:

> There is a single line called synopsis which explains what that does. I
> will add single line examples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/84#issuecomment-129216352>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
Can we please have one of these for docs. @jovo has like 2 and @willgray has 1 more.

**Comment by willgray** [comment]
What do you mean?  You want all docs in one place?  Let's chat over icecream

Best,
Will
