### ISSUE TITLE
api/ocp_types.html

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#86]
i don't understand the relationship between "channel types" and "data types"
can any channel type be any data type?

if not, maybe we need a table that specifies the allowable pairings.

also, i thought we changed "probability maps" to something else.

**Comment by kunallillaney** [comment]
http://openconnectome.github.io/open-connectome/api/ocp_types.html

**Comment by jovo** [comment]
so great!

On Fri, Aug 28, 2015 at 1:03 AM, Kunal Lillaney <notifications@github.com>
wrote:

> http://openconnectome.github.io/open-connectome/api/ocp_types.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/86#issuecomment-135636684>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York>
