### ISSUE TITLE
document how to get list of public tokens

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#88]

**Comment by kunallillaney** [comment]
http://mri.ocp.me/open-connectome/api/public_api.html#get

**Comment by kunallillaney** [comment]
@jovo Check the link above.I gave an example and expanded on the synopsis.

**Comment by jovo** [comment]
definitely better.
i'm still a bit confused.

if i type 'GET ...." into terminal or a url, i don't get the response you
said?
i expected you to provide an operational url?
maybe what you did is better/clearer, and i just had a different
expectation?

On Tue, Aug 11, 2015 at 11:51 AM, Kunal Lillaney <notifications@github.com>
wrote:

> @jovo <https://github.com/jovo> Check the link above.I gave an example
> and expanded on the synopsis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/88#issuecomment-129990506>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
I'm with Kunal that this is a better (or at least more proper) way to
document this.   It may be less obvious for neuroscientists, which may make
it a bad approach.

But it's a good way to document restful calls in general.

you just have to put the server with the get (separating the system from
the call itself)

Best,
Will

On Tue, Aug 11, 2015 at 4:22 PM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
i don't get it.
can you explain more.

can you tell me exactly what i type and where?

On Tue, Aug 11, 2015 at 2:41 PM, William Gray <notifications@github.com>
wrote:

> I'm with Kunal that this is a better (or at least more proper) way to
> document this. It may be less obvious for neuroscientists, which may make
> it a bad approach.
>
> But it's a good way to document restful calls in general.
>
> you just have to put the server with the get (separating the system from
> the call itself)
>
> Best,
> Will
>
> On Tue, Aug 11, 2015 at 4:22 PM, joshua vogelstein <
> notifications@github.com
> > wrote:
>
> > definitely better.
> > i'm still a bit confused.
> >
> > if i type 'GET ...." into terminal or a url, i don't get the response you
> > said?
> > i expected you to provide an operational url?
> > maybe what you did is better/clearer, and i just had a different
> > expectation?
> >
> > On Tue, Aug 11, 2015 at 11:51 AM, Kunal Lillaney <
> notifications@github.com
> > >
> > wrote:
> >
> > > @jovo <https://github.com/jovo> Check the link above.I gave an example
> > > and expanded on the synopsis.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-129990506
> > >
> > > .
> > >
> >
> >
> >
> > --
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> >
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130054894
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130061817>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
using the http 1.1 protocol, you type:  (host)(get command), so:

ocp.me/ocp/ca/public_tokens

Best,
Will

On Tue, Aug 11, 2015 at 4:42 PM, joshua vogelstein <notifications@github.com

**Comment by willgray** [comment]
http = meaning use a webbrowser, although certainly other tools supporting
http are ok.  :)

Best,
Will

**Comment by jovo** [comment]
i see, kinda.

i think for clarity, we would want the examples to literally specify
exactly what to type where.

it seems like 2 use cases are:
1) into browser
2) in python.

i'm open to both, or one or the other
but either way, i'd want the example to specify what to type where, which i
believe is consistent with how other packages are documented, eg, numpy and
sci-kit learn and thunder?


On Tue, Aug 11, 2015 at 2:45 PM, William Gray <notifications@github.com>
wrote:

> http = meaning use a webbrowser, although certainly other tools supporting
> http are ok. :)
>
> Best,
> Will
>
> On Tue, Aug 11, 2015 at 4:44 PM, William R. Gray Roncal <
> willgray@gmail.com>
> wrote:
>
>
> > using the http 1.1 protocol, you type: (host)(get command), so:
> >
> > ocp.me/ocp/ca/public_tokens
> >
> > Best,
> > Will
> >
> > On Tue, Aug 11, 2015 at 4:42 PM, joshua vogelstein <
> > notifications@github.com> wrote:
> >
> >> i don't get it.
> >> can you explain more.
> >>
> >> can you tell me exactly what i type and where?
> >>
> >> On Tue, Aug 11, 2015 at 2:41 PM, William Gray <notifications@github.com
> >
> >> wrote:
> >>
> >>
> >> > I'm with Kunal that this is a better (or at least more proper) way to
> >> > document this. It may be less obvious for neuroscientists, which may
> >> make
> >> > it a bad approach.
> >> >
> >> > But it's a good way to document restful calls in general.
> >> >
> >> > you just have to put the server with the get (separating the system
> from
> >> > the call itself)
> >> >
> >> > Best,
> >> > Will
> >> >
> >> > On Tue, Aug 11, 2015 at 4:22 PM, joshua vogelstein <
> >> > notifications@github.com
> >> > > wrote:
> >> >
> >> > > definitely better.
> >> > > i'm still a bit confused.
> >> > >
> >> > > if i type 'GET ...." into terminal or a url, i don't get the
> response
> >> you
> >> > > said?
> >> > > i expected you to provide an operational url?
> >> > > maybe what you did is better/clearer, and i just had a different
> >> > > expectation?
> >> > >
> >> > > On Tue, Aug 11, 2015 at 11:51 AM, Kunal Lillaney <
> >> > notifications@github.com
> >> > > >
> >> > > wrote:
> >> > >
> >> > > > @jovo <https://github.com/jovo> Check the link above.I gave an
> >> example
> >> > > > and expanded on the synopsis.
> >> > > >
> >> > > > —
> >> > > > Reply to this email directly or view it on GitHub
> >> > > > <
> >> > >
> >> >
> >>
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-129990506
> >> > > >
> >> > > > .
> >> > > >
> >> > >
> >> > >
> >> > >
> >> > > --
> >> > > the glass is all full: half water, half air.
> >> > > openconnecto.me, jovo.me, office hours
> >> > > <
> >> > >
> >> >
> >>
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> >> > > >
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <
> >> >
> >>
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130054894
> >> > >
> >> > > .
> >> > >
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130061817
> >> >
> >> > .
> >> >
> >>
> >>
> >>
> >> --
> >> the glass is all full: half water, half air.
> >> openconnecto.me, jovo.me, office hours
> >> <
> >>
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> >> >
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130062703
> >
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130064518>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
what is your user story?

RESTful APIs are more oriented for CS people rather than neuro people.

One thing that might help to bridge is for not-Kunal to make an example of
how to get public tokens with the urls, etc., but this seems beyond the
documentation that kunal is writing.

Jordan/Will can help with that as part of demos.  :)


Best,
Will

On Tue, Aug 11, 2015 at 5:28 PM, joshua vogelstein <notifications@github.com
> wrote:

> i see, kinda.
>
> i think for clarity, we would want the examples to literally specify
> exactly what to type where.
>
> it seems like 2 use cases are:
> 1) into browser
> 2) in python.
>
> i'm open to both, or one or the other
> but either way, i'd want the example to specify what to type where, which i
> believe is consistent with how other packages are documented, eg, numpy and
> sci-kit learn and thunder?
>
>
> On Tue, Aug 11, 2015 at 2:45 PM, William Gray <notifications@github.com>
>
> wrote:
>
> > http = meaning use a webbrowser, although certainly other tools
> supporting
> > http are ok. :)
> >
> > Best,
> > Will
> >
> > On Tue, Aug 11, 2015 at 4:44 PM, William R. Gray Roncal <
> > willgray@gmail.com>
> > wrote:
> >
> >
> > > using the http 1.1 protocol, you type: (host)(get command), so:
> > >
> > > ocp.me/ocp/ca/public_tokens
> > >
> > > Best,
> > > Will
> > >
> > > On Tue, Aug 11, 2015 at 4:42 PM, joshua vogelstein <

**Comment by jovo** [comment]
can somebody point me to other documentation that confirms to the way kunal
made this one?
i'm open to just being ignorant to this...

On Tue, Aug 11, 2015 at 3:34 PM, William Gray <notifications@github.com>
wrote:

> what is your user story?
>
> RESTful APIs are more oriented for CS people rather than neuro people.
>
> One thing that might help to bridge is for not-Kunal to make an example of
> how to get public tokens with the urls, etc., but this seems beyond the
> documentation that kunal is writing.
>
> Jordan/Will can help with that as part of demos. :)
>
>
> Best,
> Will
>
> On Tue, Aug 11, 2015 at 5:28 PM, joshua vogelstein <
> notifications@github.com
>
> > wrote:
>
> > i see, kinda.
> >
> > i think for clarity, we would want the examples to literally specify
> > exactly what to type where.
> >
> > it seems like 2 use cases are:
> > 1) into browser
> > 2) in python.
> >
> > i'm open to both, or one or the other
> > but either way, i'd want the example to specify what to type where,
> which i
> > believe is consistent with how other packages are documented, eg, numpy
> and
> > sci-kit learn and thunder?
> >
> >
> > On Tue, Aug 11, 2015 at 2:45 PM, William Gray <notifications@github.com>
> >
> > wrote:
> >
> > > http = meaning use a webbrowser, although certainly other tools
> > supporting
> > > http are ok. :)
> > >
> > > Best,
> > > Will
> > >
> > > On Tue, Aug 11, 2015 at 4:44 PM, William R. Gray Roncal <
> > > willgray@gmail.com>
> > > wrote:
> > >
> > >
> > > > using the http 1.1 protocol, you type: (host)(get command), so:
> > > >
> > > > ocp.me/ocp/ca/public_tokens
> > > >
> > > > Best,
> > > > Will
> > > >
> > > > On Tue, Aug 11, 2015 at 4:42 PM, joshua vogelstein <
> > > > notifications@github.com> wrote:
> > > >
> > > >> i don't get it.
> > > >> can you explain more.
> > > >>
> > > >> can you tell me exactly what i type and where?
> > > >>
> > > >> On Tue, Aug 11, 2015 at 2:41 PM, William Gray <
> > notifications@github.com
> > > >
> > > >> wrote:
> > > >>
> > > >>
> > > >> > I'm with Kunal that this is a better (or at least more proper) way
> > to
> > > >> > document this. It may be less obvious for neuroscientists, which
> may
> > > >> make
> > > >> > it a bad approach.
> > > >> >
> > > >> > But it's a good way to document restful calls in general.
> > > >> >
> > > >> > you just have to put the server with the get (separating the
> system
> > > from
> > > >> > the call itself)
> > > >> >
> > > >> > Best,
> > > >> > Will
> > > >> >
> > > >> > On Tue, Aug 11, 2015 at 4:22 PM, joshua vogelstein <
> > > >> > notifications@github.com
> > > >> > > wrote:
> > > >> >
> > > >> > > definitely better.
> > > >> > > i'm still a bit confused.
> > > >> > >
> > > >> > > if i type 'GET ...." into terminal or a url, i don't get the
> > > response
> > > >> you
> > > >> > > said?
> > > >> > > i expected you to provide an operational url?
> > > >> > > maybe what you did is better/clearer, and i just had a different
> > > >> > > expectation?
> > > >> > >
> > > >> > > On Tue, Aug 11, 2015 at 11:51 AM, Kunal Lillaney <
> > > >> > notifications@github.com
> > > >> > > >
> > > >> > > wrote:
> > > >> > >
> > > >> > > > @jovo <https://github.com/jovo> Check the link above.I gave
> an
> > > >> example
> > > >> > > > and expanded on the synopsis.
> > > >> > > >
> > > >> > > > —
> > > >> > > > Reply to this email directly or view it on GitHub
> > > >> > > > <
> > > >> > >
> > > >> >
> > > >>
> > >
> >
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-129990506
> > > >> > > >
> > > >> > > > .
> > > >> > > >
> > > >> > >
> > > >> > >
> > > >> > >
> > > >> > > --
> > > >> > > the glass is all full: half water, half air.
> > > >> > > openconnecto.me, jovo.me, office hours
> > > >> > > <
> > > >> > >
> > > >> >
> > > >>
> > >
> >
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > > >> > > >
> > > >> > >
> > > >> > > —
> > > >> > > Reply to this email directly or view it on GitHub
> > > >> > > <
> > > >> >
> > > >>
> > >
> >
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130054894
> > > >> > >
> > > >> > > .
> > > >> > >
> > > >> >
> > > >> > —
> > > >> > Reply to this email directly or view it on GitHub
> > > >> > <
> > > >>
> > >
> >
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130061817
> > > >> >
> > > >> > .
> > > >> >
> > > >>
> > > >>
> > > >>
> > > >> --
> > > >> the glass is all full: half water, half air.
> > > >> openconnecto.me, jovo.me, office hours
> > > >> <
> > > >>
> > >
> >
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > > >> >
> > > >>
> > > >> —
> > > >> Reply to this email directly or view it on GitHub
> > > >> <
> > >
> >
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130062703
> > > >
> > > >> .
> > > >>
> > > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130064518
> > >
> > > .
> > >
> >
> >
> >
> > --
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> >
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130083475
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130084708>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by jovo** [comment]
user story:

"i'm an ocpeep, and i want to find out the list of tokens without talking
to kunal."

i think this is the 'right' target audience for most of the RESTful docs.
note that most ocpeeps are not CS folk, rather, stats, computer vision,
data scientists, etc.
no ocpeeps are 'pure neuroscientists'

so something clear to smart people that know how to use computers and write
code is good.


On Tue, Aug 11, 2015 at 4:12 PM, joshua vogelstein <joshuav@gmail.com>
wrote:

> can somebody point me to other documentation that confirms to the way
> kunal made this one?
> i'm open to just being ignorant to this...
>
> On Tue, Aug 11, 2015 at 3:34 PM, William Gray <notifications@github.com>
> wrote:
>
>> what is your user story?
>>
>> RESTful APIs are more oriented for CS people rather than neuro people.
>>
>> One thing that might help to bridge is for not-Kunal to make an example of
>> how to get public tokens with the urls, etc., but this seems beyond the
>> documentation that kunal is writing.
>>
>> Jordan/Will can help with that as part of demos. :)
>>
>>
>> Best,
>> Will
>>
>> On Tue, Aug 11, 2015 at 5:28 PM, joshua vogelstein <
>> notifications@github.com
>>
>> > wrote:
>>
>> > i see, kinda.
>> >
>> > i think for clarity, we would want the examples to literally specify
>> > exactly what to type where.
>> >
>> > it seems like 2 use cases are:
>> > 1) into browser
>> > 2) in python.
>> >
>> > i'm open to both, or one or the other
>> > but either way, i'd want the example to specify what to type where,
>> which i
>> > believe is consistent with how other packages are documented, eg, numpy
>> and
>> > sci-kit learn and thunder?
>> >
>> >
>> > On Tue, Aug 11, 2015 at 2:45 PM, William Gray <notifications@github.com
>> >
>> >
>> > wrote:
>> >
>> > > http = meaning use a webbrowser, although certainly other tools
>> > supporting
>> > > http are ok. :)
>> > >
>> > > Best,
>> > > Will
>> > >
>> > > On Tue, Aug 11, 2015 at 4:44 PM, William R. Gray Roncal <
>> > > willgray@gmail.com>
>> > > wrote:
>> > >
>> > >
>> > > > using the http 1.1 protocol, you type: (host)(get command), so:
>> > > >
>> > > > ocp.me/ocp/ca/public_tokens
>> > > >
>> > > > Best,
>> > > > Will
>> > > >
>> > > > On Tue, Aug 11, 2015 at 4:42 PM, joshua vogelstein <
>> > > > notifications@github.com> wrote:
>> > > >
>> > > >> i don't get it.
>> > > >> can you explain more.
>> > > >>
>> > > >> can you tell me exactly what i type and where?
>> > > >>
>> > > >> On Tue, Aug 11, 2015 at 2:41 PM, William Gray <
>> > notifications@github.com
>> > > >
>> > > >> wrote:
>> > > >>
>> > > >>
>> > > >> > I'm with Kunal that this is a better (or at least more proper)
>> way
>> > to
>> > > >> > document this. It may be less obvious for neuroscientists, which
>> may
>> > > >> make
>> > > >> > it a bad approach.
>> > > >> >
>> > > >> > But it's a good way to document restful calls in general.
>> > > >> >
>> > > >> > you just have to put the server with the get (separating the
>> system
>> > > from
>> > > >> > the call itself)
>> > > >> >
>> > > >> > Best,
>> > > >> > Will
>> > > >> >
>> > > >> > On Tue, Aug 11, 2015 at 4:22 PM, joshua vogelstein <
>> > > >> > notifications@github.com
>> > > >> > > wrote:
>> > > >> >
>> > > >> > > definitely better.
>> > > >> > > i'm still a bit confused.
>> > > >> > >
>> > > >> > > if i type 'GET ...." into terminal or a url, i don't get the
>> > > response
>> > > >> you
>> > > >> > > said?
>> > > >> > > i expected you to provide an operational url?
>> > > >> > > maybe what you did is better/clearer, and i just had a
>> different
>> > > >> > > expectation?
>> > > >> > >
>> > > >> > > On Tue, Aug 11, 2015 at 11:51 AM, Kunal Lillaney <
>> > > >> > notifications@github.com
>> > > >> > > >
>> > > >> > > wrote:
>> > > >> > >
>> > > >> > > > @jovo <https://github.com/jovo> Check the link above.I gave
>> an
>> > > >> example
>> > > >> > > > and expanded on the synopsis.
>> > > >> > > >
>> > > >> > > > —
>> > > >> > > > Reply to this email directly or view it on GitHub
>> > > >> > > > <
>> > > >> > >
>> > > >> >
>> > > >>
>> > >
>> >
>> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-129990506
>> > > >> > > >
>> > > >> > > > .
>> > > >> > > >
>> > > >> > >
>> > > >> > >
>> > > >> > >
>> > > >> > > --
>> > > >> > > the glass is all full: half water, half air.
>> > > >> > > openconnecto.me, jovo.me, office hours
>> > > >> > > <
>> > > >> > >
>> > > >> >
>> > > >>
>> > >
>> >
>> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
>> > > >> > > >
>> > > >> > >
>> > > >> > > —
>> > > >> > > Reply to this email directly or view it on GitHub
>> > > >> > > <
>> > > >> >
>> > > >>
>> > >
>> >
>> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130054894
>> > > >> > >
>> > > >> > > .
>> > > >> > >
>> > > >> >
>> > > >> > —
>> > > >> > Reply to this email directly or view it on GitHub
>> > > >> > <
>> > > >>
>> > >
>> >
>> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130061817
>> > > >> >
>> > > >> > .
>> > > >> >
>> > > >>
>> > > >>
>> > > >>
>> > > >> --
>> > > >> the glass is all full: half water, half air.
>> > > >> openconnecto.me, jovo.me, office hours
>> > > >> <
>> > > >>
>> > >
>> >
>> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
>> > > >> >
>> > > >>
>> > > >> —
>> > > >> Reply to this email directly or view it on GitHub
>> > > >> <
>> > >
>> >
>> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130062703
>> > > >
>> > > >> .
>> > > >>
>> > > >
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130064518
>> > >
>> > > .
>> > >
>> >
>> >
>> >
>> > --
>> > the glass is all full: half water, half air.
>> > openconnecto.me, jovo.me, office hours
>> > <
>> >
>> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130083475
>> >
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130084708>
>> .
>>
>
>
>
> --
> the glass is all full:  half water, half air.
> openconnecto.me, jovo.me, office hours
> <https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by kunallillaney** [comment]
https://dev.twitter.com/rest/reference/get/statuses/mentions_timeline

**Comment by jovo** [comment]
ok.
of note, that page still has url example,
in fact, it has 2:
1) a resource url, and
2) an example

so, it seems quite standard to provide an example that one could copy and
paste into a browser (or other thing that reads http), yah?

so, if you want to do the GET xxx, that's cool, i support it
but i still think we need a good example...

On Tue, Aug 11, 2015 at 4:28 PM, Kunal Lillaney <notifications@github.com>
wrote:

> https://dev.twitter.com/rest/reference/get/statuses/mentions_timeline
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/88#issuecomment-130097156>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
