### ISSUE TITLE
document console

### ISSUE THREAD

**Issue by jovo** [openconnectome/open-connectome#89]

**Comment by kunallillaney** [comment]
http://mri.ocp.me/open-connectome/api/public_api.html#get

**Comment by jovo** [comment]
i think you meant this as a response to the other issue?

**Comment by kunallillaney** [comment]
@jovo Sorry there are so may issues you opened simultaneously.

**Comment by jovo** [comment]
no worries, my bad :)

**Comment by kunallillaney** [comment]
Same as #81
