### ISSUE TITLE
Add capability for 8-bit probability maps

### ISSUE THREAD

**Issue by willgray** [openconnectome/open-connectome#9]
Backend + API - this may be equivalent to 8-bit image upload, or nearly so...

Many times we don't need 32-bit precision on probabilities; as datasets scale, we could significantly cut down on data being transmitted/written.  Two near term use cases (cell detection and large scale synapses)

**Comment by randalburns** [comment]
I don't like the idea of an 8-bit probability.  And I think that the savings are false in transfer. I am closing.

**Comment by willgray** [comment]
peace.

Best,
Will
