### ISSUE TITLE
Example URLs in documentation don't work

### ISSUE THREAD

**Issue by kkutten1** [openconnectome/open-connectome#94]
For example the 1st url in http://w.ocp.me/tools:ocp:cutouts should be 
http://openconnecto.me/ocp/ca/kasthuri11/hdf5/1/4000,4200/4000,4200/100,300/
...instead of...
http://openconnecto.me/emca/kasthuri11/hdf5/1/4000,4200/4000,4200/100,300/

Also the url in http://mri.ocp.me/open-connectome/api/data_api.html#get-xy-slice-cutout should be
/ocp/ca/kasthuri11/xy/0/9000,9500/12000,12500/50/
...instead of...
/ocp/ca/kasthuri11/image/xy/0/9000,9500/12000,12500/50/

**Comment by willgray** [comment]
The authoritative place for this documentation is:
openconnectome.github.io/open-connectome/

w.ocp.me is depreciated and is being phased out.

I will add a note to clarify. Thanks for making this better.

Best,
Will

**Comment by jovo** [comment]
@alexbaden @willgray  - there is a bunch of good content both in w.ocp.me &
the old hssl site. maybe it makes sense for an undergrad to migrate
everything over?

On Tue, Aug 18, 2015 at 10:50 AM, William Gray <notifications@github.com>
wrote:

> The authoritative place for this documentation is:
> openconnectome.github.io/open-connectome/
>
> w.ocp.me is depreciated and is being phased out.
>
> I will add a note to clarify. Thanks for making this better.
>
> Best,
> Will
>
> On Tue, Aug 18, 2015 at 10:44 AM, kkutten1 <notifications@github.com>
> wrote:
>
> > For example the 1st url in http://w.ocp.me/tools:ocp:cutouts should be
> >
> >
> http://openconnecto.me/ocp/ca/kasthuri11/hdf5/1/4000,4200/4000,4200/100,300/
> > ...instead of...
> >
> http://openconnecto.me/emca/kasthuri11/hdf5/1/4000,4200/4000,4200/100,300/
> >
> > Also the url in
> > http://mri.ocp.me/open-connectome/api/data_api.html#get-xy-slice-cutout
> > should be
> > /ocp/ca/kasthuri11/xy/0/9000,9500/12000,12500/50/
> > ...instead of...
> > /ocp/ca/kasthuri11/image/xy/0/9000,9500/12000,12500/50/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openconnectome/open-connectome/issues/94>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/open-connectome/issues/94#issuecomment-132237993>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
This is essentially happening...we are pulling content and deleting as we
go, with pointers. Help always welcome.

**Comment by kunallillaney** [comment]
@kkutten1 They will work now. it was the old branch.
